name: Pylint

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.**'

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r req.txt
          pip install pylint

      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py')
